%define __python /usr/osxws/bin/python
%define modulename numpy
%bcond_with doc

Summary: NumPy: array processing for numbers, strings, records, and objects.
Name: python-%{modulename}
Version: 1.5.1
Release: 1%{?_dist_release}
Source0: http://downloads.sourceforge.net/%{modulename}/%{modulename}-%{version}.tar.gz
Source1: numpy-site.cfg
License: BSD
Group: Development/Languages
Group: Applications/Edutainment
URL: http://numpy.scipy.org/

Requires: apple-gcc
Requires: python = 2.6.6
Requires: /usr/osxws/bin/python2.6
Requires: python-nose
BuildRequires: apple-gcc
BuildRequires: python-devel = 2.6.6
BuildRequires: /Library/Frameworks/Python.framework/Versions/2.6/include
%if %{with doc}
BuildRequires: python-sphinx python-matplotlib
%endif
BuildRoot: %{_tmppath}/%{name}-%{version}-root
BuildArch: fat

%description
NumPy is a general-purpose array-processing package designed to efficiently manipulate large multi-dimensional arrays of arbitrary records without sacrificing too much speed for small multi-dimensional arrays. NumPy is built on the Numeric code base and adds features introduced by numarray as well as an extended C-API and the ability to create arrays of arbitrary type which also makes NumPy suitable for interfacing with general-purpose data-base applications.

There are also basic facilities for discrete fourier transform, basic linear algebra and random number generation.

%description -l ja
Numpy は汎用配列操作パッケージであり、大規模多次元配列の効率良い操作と、小規模多次元配列での過度なスピードの犠牲をともなわないように設計されています。
Numpy は Numeric のソースコードと numarray から導入された追加機能を基に作られ、拡張された C-API を持ち、汎用のデータベースと共に利用するのに最適な、任意の型を要素とする配列生成が可能です。

Numpy は離散 Fourir 変換や線形代数、乱数生成といった基礎的な機能も備えています。

%prep
%setup -q -n %{modulename}-%{version}
cp -pf %{SOURCE1} site.cfg

%build
export CC='gcc' CXX='g++' F77='gfortran' F90='gfortran'
export ARCHFLAGS="-arch i386 -arch x86_64"
python setup.py build

for f in `find $RPM_BUILD_DIR/build -type f -name __config__.py`; do
    sed -i."tmp" "s,# This file is generated by $RPM_BUILD_DIR/%{name}-%{version}/setup.py\n,,g" $f
    rm -f $f.tmp
done

%if %{with doc}
pushd doc
make html latex
pushd build/latex
make all-pdf
popd
popd
%endif

%install
rm -rf $RPM_BUILD_ROOT
export CC='gcc' CXX='g++' F77='gfortran' F90='gfortran'
export ARCHFLAGS="-arch i386 -arch x86_64"
python setup.py install --skip-build --root=$RPM_BUILD_ROOT --install-scripts=%{_bindir}

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,wheel)
%{_bindir}/*
%{python_sitelib}/*
%if %{with doc}
%doc doc/build/html
%doc doc/build/latex/numpy-user.pdf
%doc doc/build/latex/numpy-ref.pdf
%endif

%changelog
* Thu Mar  3 2011 Akihiro Uchida <uchida@ike-dyn.ritsumei.ac.jp> 1.5.1-1
- remove Requires fftw, this is no longer supported

* Fri Jan  7 2011 Akihiro Uchida <uchida@ike-dyn.ritsumei.ac.jp> 1.5.1-0
- update to 1.5.1

* Tue Nov  9 2010 Akihiro Uchida <uchida@ike-dyn.ritsumei.ac.jp> 1.5.0-1
- rebuild with documents

* Tue Nov  9 2010 Akihiro Uchida <uchida@ike-dyn.ritsumei.ac.jp> 1.5.0-0
- initial build for Mac OS X WorkShop 10.6

